export declare const node = "node";
export declare const user = "user";
export declare const event = "event";
export declare const count = "count";
export declare const events = "events";
export declare const repository = "repository";
export declare const created_on = "created time";
export declare const description = "description";
export declare const utc_created_on = "utc created time";
